# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reception_first.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ReceptionFirstBtnService(object):
    def setupUi(self, First_Page_Window):
        First_Page_Window.setObjectName("First_Page_Window")
        First_Page_Window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(First_Page_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 30, 740, 80))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 140, 740, 80))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 250, 740, 80))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 360, 740, 80))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(310, 470, 180, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        First_Page_Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(First_Page_Window)
        self.statusbar.setObjectName("statusbar")
        First_Page_Window.setStatusBar(self.statusbar)

        self.retranslateUi(First_Page_Window)
        QtCore.QMetaObject.connectSlotsByName(First_Page_Window)

    def retranslateUi(self, First_Page_Window):
        _translate = QtCore.QCoreApplication.translate
        First_Page_Window.setWindowTitle(_translate("First_Page_Window", "First_Page_Window"))
        self.pushButton.setText(_translate("First_Page_Window", "Тіркеу, Композиттік қызмет"))
        self.pushButton_2.setText(_translate("First_Page_Window", "Қысқа мерзімді оқу, Техника және кәсіптік білім беру"))
        self.pushButton_3.setText(_translate("First_Page_Window", "Мемлекеттік грант, Шағын несие"))
        self.pushButton_4.setText(_translate("First_Page_Window", "Бөлім басшысы"))
        self.pushButton_back.setText(_translate("First_Page_Window", "Артқа"))


